# -*- coding: utf-8 -*-
"""conversio_latlong_utm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uDLCkjMuuC8scpGpcEVZI2IbMlRVPAk5
"""

import os
import pandas as pd
from pyproj import Proj, transform

# Llegim el CSV carregat per veure com es diuen les columnes

df=pd.read_csv("/content/salida (1).csv")
df.head()

# Creem una funció

def convertir_csv_utm(input_csv, zone, south=True):

    # Carreguem CSV a 'files'

    df = pd.read_csv(input_csv)

    # Per eliminar espais del nom de columna; sino issubset no identificarà

    df.columns = df.columns.str.strip()

    # Verificar que las columnas necesarias existeixen

    if not {'latitude', 'longitude'}.issubset(df.columns):
        raise ValueError("El CSV ha de tenir les columnes 'latitude' i 'longitude'")

    # Definir projeccions

    wgs84 = Proj(proj="latlong", datum="WGS84")
    utm = Proj(proj="utm", zone=zone, datum="WGS84", south=south)

    # Convertir coordenades

    df['x_utm'], df['y_utm'] = zip(*df.apply(lambda row: transform(wgs84, utm, row['longitude'], row['latitude']), axis=1))

    # Construir el nom del fitxer de sortida

    nom_base, extensio = os.path.splitext(input_csv)
    output_csv = nom_base + '_UTM' + '.csv'

    # Guardar resultat en el mateix arxiu CSV

    df.to_csv(output_csv, index=False)
    print(f"Conversió completada. Arxiu actualitzat: {output_csv}")

# Executem la funció ( CANVIAR RUTA D'ACORD AMB L'ARXIU QUE CARREGUEM !!!)

convertir_csv_utm("/content/sortida (1).csv", zone=18, south=True)

# Comprovació que l'arxiu creat conté X_UTM, Y_UTM

df2=pd.read_csv("/content/salida (1)_UTM.csv")
df2.head()